### ISSUE TITLE
Try it out opened window disappear on screen resize

### ISSUE THREAD

**Issue by saadshaukat-hello** [wll8/redoc-try#6] opened 2021-01-30 01:17 UTC
1) Click on the Try it out button
2) When try it out window is opened then resize the browser window

Expected Results: Try it out window remains open

Actual Result: Try it out the window is closed and have to click twice to open it again.

**Comment by wll8** [comment] 2021-01-30 01:54
Since try.js is implemented by placing the swagger function in the position of the button when the button is clicked. The position of the button is changed after the screen is adjusted, but the position of swagger is not updated. This is a feature request with a lower priority and will be in the future The version solves this problem.

**Comment by wll8** [comment] 2023-07-19 13:32
Now you can try version [redoc-try@1.4.6](https://github.com/wll8/redoc-try/compare/1.4.4...1.4.6) to verify that the problem is fixed.

**Closed as completed** 2023-07-20 15:20 UTC
Labels: enhancement
